services:
  - mongodb
  - redis

language: node_js

node_js:
  - stable

branches:
  only:
    - master
    - develop

before_install:
  - sudo apt-get update -y
  - sudo apt-get install ffmpeg -y

install:
  - yarn install

script:
  - yarn coverage

after_success:
  - yarn coveralls
  - yarn deploy
