services:
    - mongodb
    - redis

language: node_js

node_js:
    - stable

dist: xenial

addons:
    snaps:
        - ffmpeg

cache:
    directories:
        - node_modules

branches:
    only:
        - master
        - develop

install:
    - yarn global add codecov
    - yarn install

script:
    - yarn coverage

after_success:
    - yarn codecov
    - yarn deploy
