services:
  - mongodb
  - redis

language: node_js

node_js:
  - stable

branches:
  only:
    - master
    - develop

install:
  - yarn install

script:
  - yarn test

after_success:
  - yarn coveralls
