services:
  - mongodb
  - redis

language: node_js

node_js:
  - stable

dist: focal

cache:
  directories:
    - node_modules

branches:
  only:
    - master
    - develop

before_install:
  - sudo apt-get update
  - sudo apt-get install ffmpeg -y

install:
  - yarn global add codecov
  - yarn install

script:
  - yarn coverage

after_success:
  - yarn codecov
  - yarn deploy
