version: "3.7"

services:
  express:
    deploy:
      mode: replicated
      replicas: 5
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:4000/.well-known/apollo/server-health",
        ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    container_name: express
    image: was:1.0
    restart: "unless-stopped"
  redis_db:
    image: redis:latest
    container_name: redis_db
    restart: "unless-stopped"
  proxy:
    image: nginx:latest
    container_name: proxy
    deploy:
      mode: replicated
      replicas: 3
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    restart: "unless-stopped"
