version: "3.7"

services:
    express:
        deploy:
            resources:
                limits:
                    cpus: "1"
                    memory: "2g"
            mode: replicated
            replicas: 2
        healthcheck:
            test:
                [
                    "CMD",
                    "curl",
                    "-f",
                    "http://localhost:4000/.well-known/apollo/server-health",
                ]
            interval: 10s
            timeout: 5s
            retries: 3
            start_period: 10s
        container_name: express
        image: was:latest
        restart: "unless-stopped"
        depends_on:
            - proxy
    redis_db:
        image: redis:latest
        container_name: redis_db
        restart: "unless-stopped"
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 1s
            timeout: 3s
            retries: 30
    proxy:
        image: nginx:latest
        container_name: proxy
        ports:
            - "80:80"
        deploy:
            placement:
                constraints:
                    - "node.role==manager"
            resources:
                limits:
                    memory: "4g"
                reservations:
                    memory: "1g"
            mode: replicated
            replicas: 1
        volumes:
            - ./proxy/nginx.conf:/etc/nginx/nginx.conf
        restart: "unless-stopped"
        healthcheck:
            test: curl --fail http://localhost/nginx-health || exit 1
            interval: 10s
            timeout: 5s
            retries: 3
            start_period: 10s
